# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 12.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13
    ports:
      - 80:8000
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ./src:/var/www/html:delegated
      - ../code/html/app/code:/var/www/html/app/code:delegated
      - ../code/html/app/design/frontend/Retorica:/var/www/html/app/design/frontend/Retorica:delegated
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ./env/magento-nginx.conf:/etc/nginx/conf.d/default.conf
      - sockdatamagento2:/sock

  phpfpm:
    image: markoshust/magento-php:7.1-fpm
    links:
      - db
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:7.1-fpm
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.7
    ports:
      - 3307:3306
    env_file: env/db.env
    volumes:
      - dbdatamagento2:/var/lib/mysql

volumes:
  dbdatamagento2:
  sockdatamagento2:
